"""
ISS-022 — Crash-recovery checkpoint writer.

Writes project_state.md at $CLAUDE_PROJECT_DIR/project_state.md with enough
context to resume any in-progress task after a Claude Code session crash.

Usage:
    python scripts/checkpoint_state.py               # full checkpoint
    python scripts/checkpoint_state.py --brief       # one-liner header only

Wired as a Stop hook in .claude/settings.json so it runs automatically.
Also callable mid-session: python scripts/checkpoint_state.py
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from datetime import datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIT_DIR = REPO_ROOT / "process" / "audit"
SETTINGS  = REPO_ROOT / "config" / "global_settings.json"
OUT_PATH  = REPO_ROOT / "project_state.md"


# ── helpers ────────────────────────────────────────────────────────────────────

def _git(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(
            ["git"] + cmd, cwd=str(REPO_ROOT),
            stderr=subprocess.DEVNULL, text=True,
        ).strip()
    except subprocess.CalledProcessError:
        return ""


def _last_audit_logs(n: int = 5) -> list[dict]:
    pattern = re.compile(r"^(\d{4}-\d{2}-\d{2})_(\d+)_(.+)\.md$")
    entries = []
    for f in sorted(AUDIT_DIR.glob("*.md")):
        m = pattern.match(f.name)
        if m:
            entries.append({"date": m.group(1), "id": int(m.group(2)), "slug": m.group(3), "path": f})
    entries.sort(key=lambda e: e["id"])
    return entries[-n:]


def _open_issues_from_claude_md() -> list[dict]:
    claude_md = REPO_ROOT / "CLAUDE.md"
    try:
        text = claude_md.read_text(encoding="utf-8")
    except FileNotFoundError:
        return []
    issues = []
    in_table = False
    for line in text.splitlines():
        if "| ISS-" in line and "Priority" not in line:
            in_table = True
        if in_table and line.startswith("| ISS-"):
            parts = [p.strip() for p in line.split("|") if p.strip()]
            if len(parts) >= 4:
                issues.append({
                    "id":     parts[0],
                    "prio":   parts[1],
                    "title":  parts[2],
                    "status": parts[3],
                })
        elif in_table and not line.startswith("|"):
            break
    return [i for i in issues if i["status"] == "OPEN"]


def _uncommitted_files() -> list[str]:
    out = _git(["status", "--short"])
    return [line.strip() for line in out.splitlines() if line.strip()]


def _load_settings() -> dict:
    try:
        return json.loads(SETTINGS.read_text(encoding="utf-8"))
    except Exception:
        return {}


# ── main checkpoint writer ─────────────────────────────────────────────────────

def write_checkpoint(brief: bool = False) -> None:
    now        = datetime.now()
    branch     = _git(["branch", "--show-current"]) or "unknown"
    last_commit = _git(["log", "-1", "--format=%h %s"])
    settings   = _load_settings()
    meta       = settings.get("_meta", {})
    last_logs  = _last_audit_logs(5)
    open_issues = _open_issues_from_claude_md()
    dirty      = _uncommitted_files()

    # Brief mode: just update the header timestamp (for Stop hook — low overhead)
    if brief and OUT_PATH.exists():
        text = OUT_PATH.read_text(encoding="utf-8")
        text = re.sub(
            r"^_Last checkpoint:.*$",
            f"_Last checkpoint: {now.strftime('%Y-%m-%d %H:%M:%S')}_",
            text, flags=re.MULTILINE,
        )
        OUT_PATH.write_text(text, encoding="utf-8")
        return

    p1_open = [i for i in open_issues if i["prio"] == "P1"]
    p2_open = [i for i in open_issues if i["prio"] == "P2"]

    deliveries_md = "\n".join(
        f"- `{e['id']:03d}` {e['date']} — {e['slug']}"
        for e in last_logs
    ) or "_(none found)_"

    p1_md = "\n".join(
        f"- **{i['id']}** {i['title']}"
        for i in p1_open
    ) or "_(none)_"

    p2_md = "\n".join(
        f"- {i['id']} {i['title']}"
        for i in p2_open
    ) or "_(none)_"

    dirty_md = "\n".join(f"  {f}" for f in dirty) if dirty else "  _(clean)_"

    content = f"""# Project State — AI Studio Accademia Milano

_Last checkpoint: {now.strftime('%Y-%m-%d %H:%M:%S')}_

> Auto-generated by `scripts/checkpoint_state.py` (ISS-022).
> Edit nothing here manually — it will be overwritten on next Stop.

---

## Git

| Field | Value |
|-------|-------|
| Branch | `{branch}` |
| Last commit | `{last_commit}` |
| Config version | {meta.get('version', '?')} |
| Requests processed | {meta.get('total_requests_processed', '?')} |
| Last request ID | {meta.get('last_request_id', '?')} |

### Uncommitted / staged files
{dirty_md}

---

## Last 5 deliveries

{deliveries_md}

---

## Open issues

### P1 — must fix
{p1_md}

### P2 — should fix
{p2_md}

---

## How to resume after a crash

1. Read this file to orient yourself.
2. Check `git status` — if there are uncommitted changes, review before discarding.
3. Check the last few lines of `process/audit/` to see the last completed task.
4. Re-read `CLAUDE.md` → **Delivered Requests** table for the canonical sequence.
5. Ask Claude Code: _"Continue from where you left off."_

---

_Generated by scripts/checkpoint_state.py — do not commit this file._
"""
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"[checkpoint] wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Write project_state.md checkpoint.")
    parser.add_argument("--brief", action="store_true", help="Only refresh timestamp (fast, for Stop hook)")
    args = parser.parse_args()
    write_checkpoint(brief=args.brief)
