import argparse
import json
from pathlib import Path


def daily_body(input_path: Path) -> str:
    data = json.loads(input_path.read_text(encoding="utf-8"))
    alerts = data.get("alerts", [])
    if not alerts:
        return ""

    lines = [
        f"## {len(alerts)} New S-Tier AI Repo(s) on GitHub",
        "",
        "Repos created in the last 30 days that scored **Tier S** (80+/100) by the Analyst agent.",
        "",
        "| Repo | Stars | Language | Score | Description |",
        "|------|-------|----------|-------|-------------|",
    ]
    for a in alerts:
        desc = (a.get("description") or "")[:90]
        lines.append(
            f"| [{a['full_name']}]({a['url']}) "
            f"| {a['stars']:,} | {a['language']} | **{a['score']}** | {desc} |"
        )
    lines += [
        "",
        "---",
        "_Generated by Scout -> Analyst (daily run)_",
    ]
    return "\n".join(lines)


def weekly_body(input_path: Path) -> str:
    if not Path(input_path).exists():
        return ""

    report = Path(input_path).read_text(encoding="utf-8")
    lines = report.splitlines()

    # Extract Top 10 table from the report
    top10_lines: list = []
    in_top10 = False
    for line in lines:
        if line.startswith("## Top 10"):
            in_top10 = True
            continue
        if in_top10 and line.startswith("## "):
            break
        if in_top10:
            top10_lines.append(line)

    body_lines = [
        "## Weekly GitHub AI Research Digest",
        "",
        f"Full report committed to `{input_path}`.",
        "",
        "### Top 10 Repos",
        "",
    ] + top10_lines + [
        "",
        "---",
        "_Generated by Scout -> Analyst -> Curator -> Reporter (weekly run)_",
    ]
    return "\n".join(body_lines)


def main():
    parser = argparse.ArgumentParser(description="Generate GitHub Issue body for research runs")
    parser.add_argument("--mode", choices=["daily", "weekly"], required=True)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    body = daily_body(args.input) if args.mode == "daily" else weekly_body(args.input)
    args.output.write_text(body, encoding="utf-8")
    print(f"Issue body: {len(body)} chars -> {args.output}")


if __name__ == "__main__":
    main()
