"""
ContributorScout report generator — AI Studio Accademia Milano.

Produces a markdown shortlist of potential clients for Luigi to review.
Grouped by inferred studio need (rag_knowledge_base, chatbot_app, etc.)
"""

from datetime import date
from pathlib import Path
from typing import Optional

_PRODUCT_LABELS = {
    "rag_knowledge_base":     "RAG / Knowledge Base (€29.90)",
    "chatbot_app":            "Chatbot App (€19.90)",
    "agent_deploy_streamlit": "Agent Deploy — Streamlit (€19.90)",
    "static_landing_page":    "Landing Page (€9.90)",
}


def generate_contributor_report(
    scored_users: list,
    output_path: Optional[Path] = None,
) -> str:
    today = date.today().isoformat()
    lines = [
        f"# ContributorScout — Potential Clients  {today}",
        "",
        "> Internal prospecting report. Review before any outreach. GDPR applies to EU contacts.",
        "",
        f"**Total candidates scored:** {len(scored_users)}",
        "",
    ]

    # Top 10 summary table
    top10 = scored_users[:10]
    lines += [
        "## Top 10",
        "",
        "| Tier | Login | Score | AI Signals | Inferred Need | Contact |",
        "|------|-------|-------|-----------|--------------|---------|",
    ]
    for us in top10:
        p = us.profile
        signals = ", ".join(p.ai_signal_topics[:3] + p.ai_signal_keywords[:2]) or "—"
        needs = ", ".join(us.needs_inferred[:2]) or "—"
        contact = f"[{p.email}](mailto:{p.email})" if p.email else p.url
        lines.append(
            f"| **{us.tier}** | [{p.login}]({p.url}) | {us.score} | {signals} | {needs} | {contact} |"
        )
    lines.append("")

    # Sections grouped by inferred need
    by_need: dict = {}
    for us in scored_users:
        for need in us.needs_inferred:
            by_need.setdefault(need, []).append(us)

    if by_need:
        lines.append("## By Studio Product")
        lines.append("")

    for need, users in by_need.items():
        label = _PRODUCT_LABELS.get(need, need)
        lines += [
            f"### {label}",
            "",
            "| Login | Score | Tier | Location | Languages | Recent Repos (60d) |",
            "|-------|-------|------|----------|-----------|-------------------|",
        ]
        for us in sorted(users, key=lambda x: x.score, reverse=True)[:8]:
            p = us.profile
            langs = ", ".join(p.top_languages[:3]) or "—"
            loc = p.location or "—"
            lines.append(
                f"| [{p.login}]({p.url}) | {us.score} | {us.tier} | {loc} | {langs} | {p.recent_repos_60d} |"
            )
        lines.append("")

    # Score distribution
    tiers = {"S": 0, "A": 0, "B": 0, "C": 0}
    for us in scored_users:
        tiers[us.tier] = tiers.get(us.tier, 0) + 1
    lines += [
        "## Score Distribution",
        "",
        f"S: {tiers['S']} | A: {tiers['A']} | B: {tiers['B']} | C: {tiers['C']}",
        "",
        "---",
        "*Generated by ContributorScout. Do not distribute externally.*",
    ]

    report = "\n".join(lines)
    if output_path:
        Path(output_path).write_text(report, encoding="utf-8")
        print(f"  [Reporter] Contributor report → {output_path}")
    return report
