from datetime import date
from pathlib import Path
from typing import Optional


def deduplicate(ranked: dict) -> dict:
    seen = {}
    for topic, scores in ranked.items():
        for rs in scores:
            key = rs.repo.full_name
            if key not in seen or rs.score > seen[key].score:
                seen[key] = rs
    TAXONOMY = {
        "Foundation Models": {"llm", "large-language-model", "transformer"},
        "Agentic Systems": {"ai-agents", "langchain", "llamaindex"},
        "RAG & Search": {"rag", "retrieval-augmented-generation", "vector-database", "embeddings"},
        "Generation": {"generative-ai", "diffusion-model", "multimodal"},
        "Training & Tuning": {"fine-tuning", "prompt-engineering"},
    }
    categorised = {cat: [] for cat in TAXONOMY}
    categorised["Other"] = []
    for rs in seen.values():
        placed = False
        for cat, signals in TAXONOMY.items():
            if signals & set(rs.repo.topics):
                categorised[cat].append(rs)
                placed = True
                break
        if not placed:
            categorised["Other"].append(rs)
    for cat in categorised:
        categorised[cat].sort(key=lambda x: x.score, reverse=True)
    return {k: v for k, v in categorised.items() if v}


def generate_report(
    categorised: dict,
    output_path: Optional[Path] = None,
    insights: Optional[dict[str, str]] = None,
) -> str:
    """Generate the weekly research Markdown report.

    Args:
        categorised: Output of deduplicate() — {category: [RepoScore, ...]}
        output_path: Where to write the file. None = return string only.
        insights:    Optional {full_name: insight_text} from kitai batch synthesis.
                     When provided, each repo entry gets an AI Insight block.
    """
    today = date.today().isoformat()
    all_repos = [rs for v in categorised.values() for rs in v]
    top10 = sorted(all_repos, key=lambda x: x.score, reverse=True)[:10]
    has_insights = bool(insights)

    lines = [
        f"# GitHub AI Research Report - {today}",
        "",
        "> Generated by the AIStudio GitHub Research Team"
        + (" · AI insights via kitai batch (gpt-4o-mini)" if has_insights else ""),
        "",
        "## Top 10 Picks",
        "",
        "| Tier | Repo | Stars | Language | Score |",
        "|------|------|-------|----------|-------|",
    ]
    for rs in top10:
        lines.append(
            f"| {rs.tier} | [{rs.repo.full_name}]({rs.repo.url})"
            f" | {rs.repo.stars:,} | {rs.repo.language} | {rs.score} |"
        )
    lines.append("")

    for cat, scores in categorised.items():
        lines += [f"## {cat}", ""]
        for rs in scores[:5]:
            desc = rs.repo.description[:120] if rs.repo.description else "No description."
            topics_str = ", ".join(rs.repo.topics[:6]) or "n/a"
            lines += [
                f"### [{rs.repo.name}]({rs.repo.url}) - Tier {rs.tier} ({rs.score}/100)",
                f"**{rs.repo.full_name}** - {rs.repo.stars:,} stars - {rs.repo.language}",
                f"> {desc}",
                f"**Topics:** {topics_str}",
            ]
            if has_insights:
                insight = (insights or {}).get(rs.repo.full_name)
                if insight:
                    lines += [f"", f"**AI Insight:** {insight}"]
            lines.append("")

    report = "\n".join(lines)
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
    return report
